//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomPolicies.FxCopDeltaPolicy.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Microsoft Visual Studio 8\\Team Tools\\Static Analysis Tools\\FxCop" +
            "\\FxCopCmd.exe")]
        public string FxCopCommandPath {
            get {
                return ((string)(this["FxCopCommandPath"]));
            }
            set {
                this["FxCopCommandPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RuleAssemblies {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RuleAssemblies"]));
            }
            set {
                this["RuleAssemblies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Microsoft.Globalization#CA1300</string>\r\n  <string>Microsoft.Globalization" +
            "#CA1301</string>\r\n  <string>Microsoft.Globalization#CA1302</string>\r\n  <string>M" +
            "icrosoft.Globalization#CA1303</string>\r\n  <string>Microsoft.Globalization#CA1304" +
            "</string>\r\n  <string>Microsoft.Globalization#CA1305</string>\r\n  <string>Microsof" +
            "t.Globalization#CA1306</string>\r\n  <string>Microsoft.Security#CA2116</string>\r\n " +
            " <string>Microsoft.Security#CA2117</string>\r\n  <string>Microsoft.Security#CA2105" +
            "</string>\r\n  <string>Microsoft.Security#CA2115</string>\r\n  <string>Microsoft.Sec" +
            "urity#CA2102</string>\r\n  <string>Microsoft.Security#CA2104</string>\r\n  <string>M" +
            "icrosoft.Security#CA2122</string>\r\n  <string>Microsoft.Security#CA2114</string>\r" +
            "\n  <string>Microsoft.Security#CA2123</string>\r\n  <string>Microsoft.Security#CA21" +
            "11</string>\r\n  <string>Microsoft.Security#CA2108</string>\r\n  <string>Microsoft.S" +
            "ecurity#CA2107</string>\r\n  <string>Microsoft.Security#CA2103</string>\r\n  <string" +
            ">Microsoft.Security#CA2100</string>\r\n  <string>Microsoft.Security#CA2118</string" +
            ">\r\n  <string>Microsoft.Security#CA2109</string>\r\n  <string>Microsoft.Security#CA" +
            "2119</string>\r\n  <string>Microsoft.Security#CA2106</string>\r\n  <string>Microsoft" +
            ".Security#CA2110</string>\r\n  <string>Microsoft.Security#CA2120</string>\r\n  <stri" +
            "ng>Microsoft.Security#CA2112</string>\r\n  <string>Microsoft.Security#CA2127</stri" +
            "ng>\r\n  <string>Microsoft.Security#CA2128</string>\r\n  <string>Microsoft.Security#" +
            "CA2129</string>\r\n  <string>Microsoft.Security#CA2101</string>\r\n  <string>Microso" +
            "ft.Security#CA2121</string>\r\n  <string>Microsoft.Security#CA2126</string>\r\n  <st" +
            "ring>Microsoft.Security#CA2124</string>\r\n  <string>Microsoft.Usage#CA2209</strin" +
            "g>\r\n  <string>Microsoft.Design#CA2210</string>\r\n  <string>Microsoft.Design#CA101" +
            "4</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DisabledRules {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DisabledRules"]));
            }
            set {
                this["DisabledRules"] = value;
            }
        }
    }
}
